# Atomikos datasource
datasource:
  primary:
    xa-data-source-class-name: org.h2.jdbcx.JdbcDataSource
    xa-properties:
      url: jdbc:h2:mem:my_practice
      user: rex
      password: ji394su3
spring:
  datasource:
    initialization-mode: always
    schema: classpath:db/schema-@profileActive@.sql