atomikos:
  datasource:
    common:
      borrow-connection-timeout: 180
      max-pool-size: 30
      min-pool-size: 10
    primary:
      borrow-connection-timeout: ${atomikos.datasource.common.borrow-connection-timeout}
      max-pool-size: ${atomikos.datasource.common.max-pool-size}
      min-pool-size: ${atomikos.datasource.common.min-pool-size}
      xa-data-source-class-name: org.h2.jdbcx.JdbcDataSource
      xa-properties:
        url: jdbc:h2:mem:my_practice
        user: rex
        password: ji394su3
    secondary:
      borrow-connection-timeout: ${atomikos.datasource.common.borrow-connection-timeout}
      max-pool-size: ${atomikos.datasource.common.max-pool-size}
      min-pool-size: ${atomikos.datasource.common.min-pool-size}
      xa-data-source-class-name: org.h2.jdbcx.JdbcDataSource
      xa-properties:
        url: jdbc:h2:mem:my_practice_b
        user: rex
        password: ji394su3
  properties:
    primary:
      log-base-dir: logs/atomikos
      log-base-name: atomikos-primary-log