server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://192.168.56.1:33660/my_practice?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: rex
    password: ji394su3
  h2:
    console:
      enabled: off