server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:my_practice
    driver-class-name: org.h2.Driver
    username: rex
    password: 1
    initialization-mode: always
    schema: classpath:db/schema.sql
    data: classpath:db/data/data-dev.sql