server:
  port: &port 8080
spring:
  datasource:
    url: jdbc:h2:mem:my_practice
    driver-class-name: org.h2.Driver
    username: rex
    password: 1
    initialization-mode: embedded
    schema: classpath:db/schema.sql
  h2:
    console:
      enabled: on
app:
  url: localhost
  port: *port