package com.rex.practice.dao.model;

import com.rex.practice.model.base.BaseModel;

public class RegisterToken extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register_token.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register_token.token
     *
     * @mbg.generated
     */
    private String token;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register_token.email
     *
     * @return the value of register_token.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register_token.email
     *
     * @param email the value for register_token.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register_token.token
     *
     * @return the value of register_token.token
     *
     * @mbg.generated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register_token.token
     *
     * @param token the value for register_token.token
     *
     * @mbg.generated
     */
    public void setToken(String token) {
        this.token = token;
    }
}