package com.rex.practice.dao.model;

import com.rex.practice.model.base.BaseModel;

public class UserFunctions extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_functions.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_functions.functions_id
     *
     * @mbg.generated
     */
    private String functionsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_functions.user_id
     *
     * @return the value of user_functions.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_functions.user_id
     *
     * @param userId the value for user_functions.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_functions.functions_id
     *
     * @return the value of user_functions.functions_id
     *
     * @mbg.generated
     */
    public String getFunctionsId() {
        return functionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_functions.functions_id
     *
     * @param functionsId the value for user_functions.functions_id
     *
     * @mbg.generated
     */
    public void setFunctionsId(String functionsId) {
        this.functionsId = functionsId;
    }
}