package com.rex.practice.dao.model;

import com.rex.practice.model.base.BaseModel;

public class UserFunction extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_function.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_function.function_id
     *
     * @mbg.generated
     */
    private String functionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_function.user_id
     *
     * @return the value of user_function.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_function.user_id
     *
     * @param userId the value for user_function.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_function.function_id
     *
     * @return the value of user_function.function_id
     *
     * @mbg.generated
     */
    public String getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_function.function_id
     *
     * @param functionId the value for user_function.function_id
     *
     * @mbg.generated
     */
    public void setFunctionId(String functionId) {
        this.functionId = functionId;
    }
}