package com.rex.my.dao.mapper.primary;

import com.rex.my.dao.entity.primary.AccountType;
import java.util.List;

public interface AccountTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_type
     *
     * @mbg.generated
     */
    int insert(AccountType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_type
     *
     * @mbg.generated
     */
    AccountType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_type
     *
     * @mbg.generated
     */
    List<AccountType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AccountType record);
}