package com.rex.practice.dao.model.primary;

import com.rex.practice.model.base.BaseModel;

public class Function extends BaseModel {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function.icon
     *
     * @mbg.generated
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function.parent_id
     *
     * @mbg.generated
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function.sorted
     *
     * @mbg.generated
     */
    private Short sorted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function.id
     *
     * @return the value of function.id
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function.id
     *
     * @param id the value for function.id
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function.name
     *
     * @return the value of function.name
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function.name
     *
     * @param name the value for function.name
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function.url
     *
     * @return the value of function.url
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function.url
     *
     * @param url the value for function.url
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function.icon
     *
     * @return the value of function.icon
     * @mbg.generated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function.icon
     *
     * @param icon the value for function.icon
     * @mbg.generated
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function.parent_id
     *
     * @return the value of function.parent_id
     * @mbg.generated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function.parent_id
     *
     * @param parentId the value for function.parent_id
     * @mbg.generated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function.sorted
     *
     * @return the value of function.sorted
     * @mbg.generated
     */
    public Short getSorted() {
        return sorted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function.sorted
     *
     * @param sorted the value for function.sorted
     * @mbg.generated
     */
    public void setSorted(Short sorted) {
        this.sorted = sorted;
    }

}