@startuml
start
    if(是否有該token資料) then (Y)
        if(token是否已過期) then (Y)
            :導向提示頁;
            :刪除token資料;
            (A)
            detach
        else (N)
            :更新使用者驗證狀態;
            :刪除token資料;
            :導向登入頁;
        endif
    else (N)
        if(有註冊資料) then (Y)
            :導向提示頁;
            (A)
            detach
        else (N)
            :導向註冊頁;
            note right
                未註冊
            end note
        endif
    endif
end
(A)
if(是否重新發送認證信) then (Y)
    :重新發送認證信;
    note left
        重新認證
    end note
    detach
else (N)
    if(是否有註冊資料) then (Y)
        :刪除已註冊Email;
    else (N)
    endif
    :導向註冊頁;
    note right
        刪帳號重新註冊
    end note
endif
stop
@enduml