@startuml
start
    if(註冊資料檢核通過？) then (Y)
        if(Email是否已被註冊？) then (Y)
            if(Email是否已通過驗證？) then (Y)
                (A)
                detach
            else (N)
                (B)
                detach
            endif
        else (N)
            :執行註冊;
            :發送Email驗證信;
            (B)
            detach
        endif;
    else (N)
        (A)
    endif
(A)
:顯示錯誤訊息;
:回註冊頁;
end
(B)
:顯示提示訊息;
:回登入頁;
end
@enduml